version: '3.8'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: graphql_server_demo
    ports:
      - '5432:5432'
    volumes:
      - 'upline-db:/var/lib/postgresql/data'

  server:
    build:
      context: .
    depends_on:
      - postgres
    environment:
      PORT: 5000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_NAME: graphql_server_demo
      NODE_ENV: production
    ports:
      - '5000:5000'

volumes:
  upline-db:
