# This file is used to build local prodution docker image
FROM node:14.15.4-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

# build app
COPY tsconfig.json ./
COPY src ./src/
RUN npm run build

COPY .env ./

ENTRYPOINT ["npm", "start"]
