version: '3.8'
services:
  dev-server:
    build:
      context: .
      dockerfile: 'Dockerfile.local.dev'
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    ports:
      - '${PORT}:${PORT}'
